environment:
  nuget_apikey:
    secure: Bvblx9A9AMTXl4LdQe4Aljoy1WBh48/U3UnlCSxDenF8X6tXEDLqzHdt3krnt7R6
image: Visual Studio 2017
install:
- pwsh: .\buildscripts\install.ps1
build_script:
- pwsh: .\buildscripts\build.ps1
after_test:
- pwsh: .\buildscripts\publish.ps1